#!/bin/ksh
#++
#
# compile
#
./make_modules1
./make_modules2
./make_preproc
./make_chief
./make_print
#
# create binaries
#
./build_preproc
./build_wam
./build_pgrid
./build_pspec
./build_ptime
./build_prad
#
