#!/bin/sh
set -ex
. ${0%/*}/.dirset
path_o=${PRODADMDIR}/obj
path_f=${PRODADMDIR}/src/wind

modfile="bmvbs_wind newdat spldat fn_dwd"

cd $path_o

for code in $modfile
do
   rm -f ${code}.f90 ${code}.o
   cp ${path_f}/${code}.f90 .
   f90 -c ${code}.f90 -lmass 
   rm -f ${code}.f90
done
