#!/usr/bin/ksh -l
#
#==>  WAM model run
#
#     Arno Behrens (March 2014)
#
#PBS -q xc_normal
#PBS -l select=1
#PBS -l place=pack
#PBS -l walltime=00:05:00
#PBS -j oe
#PBS -N WAM
#
set +k
cdir=/e/uhome/gkssbeh/WAM
work=/e/uhome/gkssbeh/WAM/workdir
#
cd ${work}/tempsg
cp ${cdir}/const/Fine_2/WAM_User .
cp ${cdir}/const/ICE_INPUT.DAT .
cp ${cdir}/const/CURRENT_INPUT.DAT .
cp ${cdir}/const/TOPO_INPUT.DAT .
#cp ${cdir}/const/OBS* .
cp ${work}/work/Grid_info_fine_2_GRID .
cp ${cdir}/const/WIND_INPUT.DAT .
#
cp ${cdir}/abs/wam wam.exe

export ATP_ENABLED=1
export OMP_NUM_THREADS=1

aprun -n 4 -N 4 -j 1 -d 1 -m 1000M wam.exe
#
cp logfile.0 ${cdir}/dayfiles/wam_prot_f2
mv BLS* MAP* OUT* RAD* C* ..
#rm wam.exe WAM_User WAM_Prot w2* log* Grid_info_SWAMP
#
