#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf
   
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/pnetcdf.mk $OBJDIR
cd $OBJDIR
make -f pnetcdf.mk pnetcdf
mv pnetcdf $EXECDIR
rm -f pnetcdf.mk
