#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf

SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/pspec.mk $OBJDIR
cd $OBJDIR
make -f pspec.mk pspec
mv pspec $EXECDIR
rm -f pspec.mk
