#!/bin/sh
set -ex
. ${0%/*}/.dirset
path_o=${PRODADMDIR}/obj
path_f=${PRODADMDIR}/src/print
    
module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf

modfile="wam_netcdf_module make_netcdf"

cd $path_o

for code in $modfile
do
   rm -f ${code}.f90 ${code}.o
   cp ${path_f}/${code}.f90 ${path_o}/${code}.f90
   mpiifort -c ${code}.f90 -I/project/opt/software/netcdf/4.7.0/intel/include/ -L/project/opt/software/netcdf/4.7.0/intel/lib/ -lnetcdf -lnetcdff
   rm -f ${code}.f90
done
