#!/usr/bin/ksh -l
#
#==>  WAM model run
#
#     Arno Behrens (March 2014)
#
#PBS -q xc_normal
#PBS -l select=4
#PBS -l place=scatter
#PBS -l walltime=00:10:00
#PBS -j oe
#PBS -N WAM
#
set +k
cdir=/e/uhome/gkssbeh/WAM
work=/e/uhome/gkssbeh/WAM/workdir
#
cd ${work}/tempsg
cp ${cdir}/const/Fine_1/WAM_User WAM_User
#cp ${cdir}/const/ICE_INPUT.DAT .
#cp ${cdir}/const/CURRCAT.DAT .
#cp ${cdir}/const/OBS* .
cp ${work}/work/Grid_info_fine_1_GRID .
cp ${cdir}/const/WIND_INPUT.DAT .
#
cp ${cdir}/abs/wam wam.exe
#
export ATP_ENABLED=1
export OMP_NUM_THREADS=1

aprun -n 4 -N 1 -j 1 -d 1 -m 1000M wam.exe
#
cp logfile.0 ${cdir}/dayfiles/wam_prot_f1
mv BLS* MAP* OUT* RAD* C* ..
#rm wam.exe WAM_User WAM_Prot w2* log* Grid_info_SWAMP
#
