#!/bin/bash
#
#==>  WAM post-processing pgrid
#
#     Arno Behrens (May 2019)
#
#SBATCH --job-name=pgrid
#SBATCH --partition=pCluster
#SBATCH --ntasks=1
#SBATCH --time=00:30:00
#SBATCH --mail-type=FAIL
#SBATCH --account=cluster
#SBATCH --output=wam.o%j
#SBATCH --error=wam.e%j
#
module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf
#
set -k
WAMDIR=/gpfs/home/behrens/WAM_Cycle_6
WORK=/gpfs/work/behrens/WAM_Cycle_6
cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/Coarse_Grid/JAN/Grid_User .
cp ${WAMDIR}/abs/pgrid pgrid.exe
#
./pgrid.exe
mv Grid_Prot ${WAMDIR}/dayfiles/pgrid_prot_coarse_JAN
rm Grid_User pgrid.exe
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
