#!/bin/bash
#
#==>  WAM pre-processing preproc
#
#     Arno Behrens (May 2019)
#
#SBATCH --job-name=preproc
#SBATCH --partition=pCluster
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:05:00
#SBATCH --mail-type=FAIL
#SBATCH --account=cluster
#SBATCH --output=preproc.o%j
#SBATCH --error=preproc.e%j
#
module load compilers/intel/2019.4.243
module load intelmpi/2019.4.243
module load netcdf
#
set +k
WAMDIR=/gpfs/home/behrens/WAM_Cycle_6
WORK=/gpfs/work/behrens/WAM_Cycle_6
#
cd ${WORK}/tempsg
cp ${WAMDIR}/const/TOPOCAT.DAT .
cp ${WAMDIR}/const/Coarse_Grid/JAN/Preproc_User .
cp ${WAMDIR}/abs/preproc preproc.exe
#
srun ./preproc.exe
#
mv Preproc_Prot ${WAMDIR}/dayfiles/preproc_prot_coarse_JAN
mv Grid_info_COARSE_GRID ../work
rm Preproc_User preproc.exe TOPOCAT.DAT
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PREPROC.
# ===================================================================
#
