#!/usr/bin/ksh -l
#
#==>  WAM post-processing pspec
#
#     Arno Behrens (March 2014)
#
#PBS -q xc_normal
#PBS -l select=1
#PBS -l place=pack
#PBS -l walltime=00:10:00
#PBS -j oe
#PBS -N Pspec
#
set -k
WAMDIR=/e/uhome/gkssbeh/WAM
WORK=/e/uhome/gkssbeh/WAM/workdir
cd ${WORK}/tempsg
cp ${WAMDIR}/const/Coarse_Grid/Spectra_User .
cp ${WAMDIR}/abs/pspec pspec.exe
#
./pspec.exe
mv Spectra_Prot ${WAMDIR}/dayfiles/pspec_prot_c
rm Spectra_User pspec.exe
#
# ===================================================================
#  SPEC FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
