#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intel
module load openmpi_ib
module load netcdf
      
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/prad.mk $OBJDIR
cd $OBJDIR
make -f prad.mk prad
mv prad $EXECDIR
rm -f prad.mk
