#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intel
module load openmpi_ib
module load netcdf
    
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/chief.mk $OBJDIR
cd $OBJDIR
make -f chief.mk chief
mv chief $EXECDIR/wam
rm -f chief.mk
