#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intel
module load openmpi_ib
module load netcdf
     
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/pnetcdf_rad.mk $OBJDIR
cd $OBJDIR
make -f pnetcdf_rad.mk pnetcdf_rad
mv pnetcdf_rad $EXECDIR
rm -f pnetcdf_rad.mk
