#!/bin/sh
set -ex
. ${0%/*}/.dirset
path_o=${PRODADMDIR}/obj
path_f=${PRODADMDIR}/src/print

module load intel
module load openmpi_ib
module load netcdf

modfile="wam_netcdf_module make_netcdf"

cd $path_o

for code in $modfile
do
   rm -f ${code}.f90 ${code}.o
   cp ${path_f}/${code}.f90 ${path_o}/${code}.f90
   mpif90 -c ${code}.f90 -I$NETCDFHOME/include -L$NETCDFHOME/lib -lnetcdf -lnetcdff
   rm -f ${code}.f90
done
