#!/bin/sh
set -ex
. ${0%/*}/.dirset
path_o=${PRODADMDIR}/obj
path_f=${PRODADMDIR}/src/mp

module load intel
module load openmpi_ib
module load netcdf

modfile="mpi_decomp expand_string mpi_crtbl mpi_exchng mpi_gather_block \
mpi_gather_bound mpi_gather_grid mpi_gather_spp mpi_gather_fl"

cd $path_o

for code in $modfile
do
   rm -f ${code}.f90 ${code}.o
   cp ${path_f}/${code}.f90 ${path_o}/${code}.f90
   mpif90 -c ${code}.f90
   rm -f ${code}.f90
done
