#!/usr/bin/ksh -l
#++
#
# compile
#
module load cray-netcdf/4.3.0
module load /usr/local/pkg/modulefiles/grib_api/1.11.0
module load /usr/local/pkg/modulefiles/libdwd/1.1.6
#   
./make_modules1
./make_modules2
./make_preproc
./make_chief
./make_print
./make_netcdf
#
# create binaries
#
./build_preproc
./build_wam
./build_pgrid
./build_pspec
./build_ptime
./build_prad
./build_pnetcdf
#
